apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ferry.fullname" . }}
  labels:
    {{- include "ferry.labels" . | nindent 4 }}
data:
  ferry.toml: |
    {{- include "ferry.toml" . | nindent 4 }}
