apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ferry.fullname" . }}-cache
  labels:
    {{- include "ferry.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.cache.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.cache.size | quote }}
